# https://github.com/marketplace/actions/auto-assign-action
# Additional settings that can be used here include auto assignees, multiple/group reviewer lists, filter drafts

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
    - ysaito8015 # user
    - ironwest # user
    - hitomik723 # user

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

# A list of keywords to skip process that adds reviewers if pull requests include it
# skipKeywords:
#   - wip
